### ISSUE TITLE
Can't install package via composer

### ISSUE THREAD

**Issue by niloofarfs** [peynman/FaraPayamak#1]
Hi!
I can't install this package with following command:
`$ composer require peynman/FaraPayamak`
I get this error:

> Could not find a matching version of package peynman/FaraPayamak.

**Comment by peynman** [comment]
add this repo to your composer.json file:

"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/peynman/FaraPayamak"
        }
    ],
